CREATE TABLE IF NOT EXISTS `totals` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `condorId` varchar(24) default NULL,
  `dagNode` varchar(80) default NULL,
  `executionHost` varchar(80) default NULL,
  `slotName` varchar(10) default NULL,
  `submitTime` datetime default NULL,
  `executionStartTime` datetime default NULL,
  `executionStopTime` datetime default NULL,
  `updateImageSize` int(11) default NULL,
  `updateMemoryUsageMb` int(11) default NULL,
  `updateResidentSetSizeKb` int(11) default NULL,
  `userRunRemoteUsage` int(11) default NULL,
  `sysRunRemoteUsage` int(11) default NULL,
  `finalDiskUsageKb` int(11) default NULL,
  `finalDiskRequestKb` int(11) default NULL,
  `finalMemoryUsageMb` int(11) default NULL,
  `finalMemoryRequestMb` int(11) default NULL,
  `bytesSent` int(11) default NULL,
  `bytesReceived` int(11) default NULL,
  `terminationTime` datetime default NULL,
  `terminationCode` varchar(3) default NULL,
  `terminationReason` varchar(4096) default NULL,
  `firstSubmitTime` datetime default NULL,
  `totalBytesSent` int(11) default NULL,
  `totalBytesReceived` int(11) default NULL,
  `submissions` int(11) default NULL,
  `executions` int(11) default NULL,
  `shadowException` int(11) default NULL,
  `socketLost` int(11) default NULL,
  `socketReconnectFailure` int(11) default NULL,
  `socketReestablished` int(11) default NULL,
  `evicted` int(11) default NULL,
  `aborted` int(11) default NULL,
  `slotsUsed` int(11) default NULL,
  `hostsUsed` int(11) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
